# Generated by Django 4.2.4 on 2023-08-27 09:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0002_alter_post_text_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text_ads',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(),
        ),
    ]
