# Generated by Django 4.2.4 on 2023-08-27 10:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0003_alter_ads_text_ads_alter_post_text_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text_ads',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
