# Generated by Django 4.2.4 on 2023-08-27 11:56

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0005_alter_ads_text_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text_ads',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст объявления'),
        ),
    ]
